# Global default configuration values which are shared across roles.
# Note each role can have its own default configuration under the role's default folder.
---
# Location to store generated SSL certs and keys.
ssl_dir: "{{ inventory_dir }}/security/ssl"
# Location to store generated SSH keys.
ssh_dir: "{{ inventory_dir }}/security/ssh"
# Number of days generated certs should be valid.
cert_days: 3650
# Location to read WSGI web apps.
wsgi_apps: "{{ inventory_dir }}/wsgi_apps"
# Server root for WSGI web apps.
wsgi_server_root: /usr/local/share/wsgi_apps
# Root location for staging configuration files that will be copied to the server.
staging_root: "{{ inventory_dir }}/staging"
# Location to read gunicorn configuration files.
# These will be copied to the /etc/gunicorn.d/ location on the server.
gunicorn_staging: "{{ staging_root }}/gunicorn.d"
# Location to read nginx configuration files.
# These will be copied to the /etc/nginx/sites-available/ location and linked to sites-enabled.
nginx_staging: "{{ staging_root }}/nginx_sites"
# Location to read service sources.
device_services: "{{ inventory_dir }}/device_services"
# Location to read supervisor configuration files.
# These will be copied to the /etc/supervisor/conf.d/ location.
supervisor_staging: "{{ staging_root }}/supervisor"
# Location to store services on device.
device_services_root: /usr/local/share/device_services
