---
- name: Install mosquitto apt repository key.
  apt_key: url=http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
- name: Install mosquitto apt repository.
  apt_repository: repo="deb http://repo.mosquitto.org/debian stable main"
- name: Install mosquitto clients.
  apt: name=mosquitto-clients state=latest
- name: Install PIP.
  apt: name=python-pip state=latest
- name: Install Paho MQTT Python client.
  pip: name=paho-mqtt
- name: Install mosquitto python bindings.
  apt: name=python-mosquitto state=latest
- name: Copy CA cert.
  copy: "src={{ ssl_dir }}/mqtt_ca.crt dest=/etc/mosquitto/ca_certificates/"
- name: Copy client cert.
  copy: "src={{ ssl_dir }}/mqtt_client.crt dest=/etc/mosquitto/certs/"
- name: Copy client key.
  copy: "src={{ ssl_dir }}/mqtt_client.key dest=/etc/mosquitto/certs/"