---
- hosts: local
  gather_facts: no
  roles:
  - provision_ec2
  - gen_mqtt_certs
  - gen_ssl_certs
  - gen_wsgi_apps
- hosts: broker
  sudo: yes
  roles:
  - freedns
  - mqtt_server
  - mqtt_client/common
  - mqtt_client/ubuntu
  - web_server
  - security
  - smtp_email
  - wsgi_apps
