---
- hosts: local
  roles:
  - gen_services
- hosts: device
  sudo: yes
  roles:
  - mqtt_client/common
- hosts: Ubuntu
  gather_facts: no
  sudo: yes
  roles:
  - mqtt_client/ubuntu
- hosts: Debian
  gather_facts: no
  sudo: yes
  roles:
  - mqtt_client/debian
- hosts: device
  gather_facts: no
  sudo: yes
  roles:
  - device_services
