# Provision a single Amazon EC2 instance as the device cloud broker.
---
- hosts: local
  gather_facts: False
  tasks:
  - name: Provision server in Amazon EC2.
    ec2: image={{ image }}
         instance_type={{ instance_type }}
         aws_access_key={{ access_key }}
         aws_secret_key={{ secret_key }}
         keypair={{ keypair }}
         instance_tags='{"broker":"True"}'
         region={{ region }}
         group={{ group }}
         wait=true
         exact_count=1
         count_tag="broker"
    register: ec2_info
  - name: Associate elastic IP with server.
    ec2_eip: instance_id={{ ec2_info.tagged_instances[0].id }} 
             public_ip={{ elastic_ip }}
             aws_access_key={{ access_key }}
             aws_secret_key={{ secret_key }}
             region={{ region }}
    when: elastic_ip is defined
  - name: Register server as broker.
    add_host: hostname={{ item.public_ip }} 
              groupname=broker
              ansible_ssh_user={{ username }}
              ansible_ssh_private_key_file={{ private_key }}
    with_items: ec2_info.tagged_instances
  - name: Wait for server to have SSH running.
    wait_for:
      state=started
      host={{ item.public_ip }}
      port=22
    with_items: ec2_info.tagged_instances
