---
- name: Copy FreeDNS update script.
  template: src=afraid.aws.sh.j2 dest=/etc/cron.d/afraid.aws.sh owner=root mode=500
  when: freedns_update is defined
- name: Setup FreeDNS cron job.
  cron: minute="*/10" job="/etc/cron.d/afraid.aws.sh >/dev/null" name="FreeDNS update"
  when: freedns_update is defined
- name: Delete FreeDNS script old IP file.
  file: path=/tmp/ip.tmpfile state=absent
  when: freedns_update is defined
- name: Run FreeDNS update script.
  command: /etc/cron.d/afraid.aws.sh
  when: freedns_update is defined