---
- name: Install gunicorn.
  apt: name=gunicorn state=latest
- name: Synch WSGI apps.
  synchronize: src={{ wsgi_apps }}/ dest={{ wsgi_server_root }}/ recursive=yes mode=push delete=yes
- name: Install python PIP.
  apt: name=python-pip state=latest
- name: Get list of PIP package dependencies.
  command: cat {{ wsgi_server_root }}/pip_packages
  register: packages
- name: Install PIP packages.
  pip: name={{ item }}
  with_items: packages.stdout_lines
- name: Copy gunicorn configs.
  copy: src={{ gunicorn_staging }}/ dest=/etc/gunicorn.d/
- name: Restart gunicorn.
  service: name=gunicorn state=restarted enabled=yes
- name: Copy nginx configs.
  copy: src={{ nginx_staging }}/ dest=/etc/nginx/sites-available
- name: Enable nginx configs.
  file: src=/etc/nginx/sites-available/{{ item | basename }} dest=/etc/nginx/sites-enabled/{{ item | basename }} state=link
  with_fileglob: "{{ nginx_staging }}/*.conf"
- name: Restart nginx.
  service: name=nginx state=restarted enabled=yes